### ISSUE TITLE
On chrome linux slideshare view is broken

### ISSUE THREAD

**Issue by rvanderwerf** [ffissore/presentz.js#27]
On edit mode of my presentation using slideshare, it just says 'loading' and never shows any slides. Any links on there are broken. Also if I click 'this thing is slow and I know what I am doing' and I upload a csv in the format "timeinseconds,slideindex" it shows in the preview, but if I click 'go with this' green button, it does nothing and I am stuck at dead end.

Love the idea but it can't seem to get all the way through using youtube + slideshare combo. I have 26 slides on the deck not sure if that matters. I tried slide index 0 based or 1 based but no difference. I'd saved under my account as 'spring boot w/vasu...' if you want to try it out.

**Comment by ffissore** [comment]
Yes, Slideshare has dropped their flash player api.
I've removed SlideShare plugin from the list of default ones. SlideShareOEmbed should work, although you'll miss the slideshare frame and graphics around the slides
