### ISSUE TITLE
Html5 not working

### ISSUE THREAD

**Issue by AlexObreja** [ffissore/presentz.js#32]
Hi, i'm trying to load html5 video selfhosted using the MediaElement Library but without success. Other libraries are working but only Html5 not. I think the problem it's where

`
playerOptions = {
        timerRate: 500,
        success: (function(_this) {
          return function(me) {
            _this.onPlayerLoaded(me);
          };
        })(this)
      };
      new MediaElementPlayer("#" + this.elementId, playerOptions);`

Return function is not loading and i don't really know how to make it load.

Here my Json and JS:

`<script type="text/javascript">
    var presentation;
    var presentz;

    function initPresentz(pres) {
        console.log(pres);
        presentation = pres;

        presentz = new Presentz("#player_video", "460x420", "#slideshow_player", "460x420")
        presentz.init(presentation);
        presentz.on("slidechange", function (prevChap, prevSlide, chap, slide) {
            console.log('slideChange');
            $("#chapter").text("At chapter " + chap + ", slide " + slide);
        });
        presentz.changeChapter(0, 0, true, function (err) {
            console.log('chapterChange');
            if (err) {
                alert(err);
            }
        });
    }

    $(document).ready(function () {
        initPresentz({
            "title": "Test corso Upload video PDF",
            "chapters": [
                {
                    "duration": 218,
                    "video": {
                        "url": "http://elearning.local/uploads/course/chapter/video/iPhone_X_—_Introducing_iPhone_X_—_Apple.mp4"

                    },
                    "slides": [                        {
                            "url": "http://elearning.local/uploads/course/chapter/pdf/converted/Lanieri-guide-it-v2.pdf-0.jpg",
                            "time": 0                        },
                                            {
                            "url": "http://elearning.local/uploads/course/chapter/pdf/converted/Lanieri-guide-it-v2.pdf-1.jpg",
                            "time": 1                        },
                                            {
                            "url": "http://elearning.local/uploads/course/chapter/pdf/converted/Lanieri-guide-it-v2.pdf-2.jpg",
                            "time": 2                        },
                                            {
                            "url": "http://elearning.local/uploads/course/chapter/pdf/converted/Lanieri-guide-it-v2.pdf-3.jpg",
                            "time": 3                        },
                                            {
                            "url": "http://elearning.local/uploads/course/chapter/pdf/converted/Lanieri-guide-it-v2.pdf-4.jpg",
                            "time": 4                        },
                                            {
                            "url": "http://elearning.local/uploads/course/chapter/pdf/converted/Lanieri-guide-it-v2.pdf-5.jpg",
                            "time": 5                        },
                                            {
                            "url": "http://elearning.local/uploads/course/chapter/pdf/converted/Lanieri-guide-it-v2.pdf-6.jpg",
                            "time": 6                        },
                                            {
                            "url": "http://elearning.local/uploads/course/chapter/pdf/converted/Lanieri-guide-it-v2.pdf-7.jpg",
                            "time": 7                        },
                    ]
                }
            ]
        });
    });
</script>`

**Comment by AlexObreja** [comment]
Found the issue. You need to change the line 416 without the hashtag from this
`Html5Video.prototype.changeVideo = function(videoData, wouldPlay1) {
            var $videoContainer, playerOptions;
            this.wouldPlay = wouldPlay1;
            $videoContainer = jQuery(this.videoContainer);
            $videoContainer.empty();
            $videoContainer.append("<video id=\"" + this.elementId + "\" controls preload=\"none\" src=\"" + videoData.url + "\" width=\"100%\" height=\"100%\"></video>");
            playerOptions = {
                timerRate: 500,
                success: (function(_this) {
                    return function(me) {
                        _this.onPlayerLoaded(me);
                    };
                })(this)
            };
            new MediaElementPlayer("#" + this.elementId, playerOptions);
        };`

to this:

`Html5Video.prototype.changeVideo = function(videoData, wouldPlay1) {
            var $videoContainer, playerOptions;
            this.wouldPlay = wouldPlay1;
            $videoContainer = jQuery(this.videoContainer);
            $videoContainer.empty();
            $videoContainer.append("<video id=\"" + this.elementId + "\" controls preload=\"none\" src=\"" + videoData.url + "\" width=\"100%\" height=\"100%\"></video>");
            playerOptions = {
                timerRate: 500,
                success: (function(_this) {
                    return function(me) {
                        _this.onPlayerLoaded(me);
                    };
                })(this)
            };
            new MediaElementPlayer(this.elementId, playerOptions);
        };`

**Comment by ffissore** [comment]
Why did you close the issue? Was it invalid?
If it was valid as I think it is, would you like to share your fix with a pull request?

**Comment by AlexObreja** [comment]
Hy Federico, because i fixed it. I wrote a comment for the fix but i didn't made a pull request. I can do it. The line i've edited was the 416 removing the hashtag. Give me a minute and i'll make the pull request

**Comment by AlexObreja** [comment]
By the way, very great job. I'll continue to improve the repository with my suggestions in future. I'm using it for a project sharing all the credits to the repo.
